name: Gerador ReaPack Index

on:
  push:
    branches:
      - main
      - master

jobs:
  reapack-index:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4
      
      - name: Rodar o reapack-index
        uses: cfillion/reapack-index@v1
        with:
          commit-message: "🤖 Atualização automática do index.xml"
